- name: app-setup
  include_role:
    name: common
    tasks_from: app-setup
  
- name: nodejs setup
  include_role: 
    name: common
    tasks_from: nodejs

- name: systemctl setup
  include_role:
    name: common
    tasks_from: systemctl

- name: copying mongo repo for clinet installation
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.command: mongosh --host mongodb.rajeshit.space --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output
  ignore_errors: yes

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"
  ignore_errors: yes

- name: load products
  ansible.builtin.shell: mongosh --host mongodb.rajeshit.space < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0
  ignore_errors: yes

- name: "{{ component }} deployment "
  tags:
  - import
  import_role:
    name: common
    tasks_from: nodejs-deployment
