#!/bin/bash

- name: "stop the {{ component }}service"
  ansible.builtin.service:
    name: "{{ component }}"
    state: stopped

- name: remove /app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create /app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download the application
  ansible.builtin.unarchive:
    src: "https://roboshop-backend-src.s3.us-east-1.amazonaws.com/{{ component }}-v3.zip"
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app

- name: restart service
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted

    
